### ISSUE TITLE
Simple Crash with CloudRail fails

### ISSUE THREAD

**Issue by XJ-Code** [CloudRail/cloudrail-si-objc-sdk#1]
I am trying to implement an application that includes downloading files from Dropbox 、 One Drive and Google Drive. It looks like there is a crash straightforward framework that does that (CloudRail). But the codes crashes when I try to work with the file login if i click the 'cancel' button. if i can't connect the net work ,it also crash and tell me NSURLConnection finished with error - code -1200;

**Comment by fel-cesar** [comment]
@XJ-Code Are you using the simple or the advanced authentication? (can you share a bit of your code?)

**Comment by fel-cesar** [comment]
I've just tested and could not replicate the "crash" if you click the cancel button, an exception is thrown (that should be captured). Also tested with no internet connection and the app does not crash, it simply does not load the web view (used in the authentication process). Are you wrapping the calls into a @try @catch block? 

```objc
CRDropbox * dropbox = [[CRDropbox alloc] initWithClientId:@"" clientSecret:@""];
  @try{
   [dropbox login];
    NSString * userLogin = [dropbox userLogin];
    NSLog(@"--%@--", userLogin);
  } @catch (NSException * exception){
    NSLog(@"--Exception thrown:%@--", exception.reason);
  }
```

**Comment by fel-cesar** [comment]
Duplicated from [here](https://github.com/CloudRail/cloudrail-si-ios-sdk/issues/29).
